### ISSUE TITLE
提示找不到'DataProcessor':No module named 'DataProcessor'

### ISSUE THREAD

**Issue by panghaoyu** [rootlu/MetaHIN#5]
你好，感谢分享代码，我运行main.py后有如下提示：
`Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from DataHelper import DataHelper
  File "/content/gdrive/My Drive/Colab Notebooks/PaperCode/MetaHIN-master/code/DataHelper.py", line 8, in <module>
    from DataProcessor import Movielens
ModuleNotFoundError: No module named 'DataProcessor'`
请问是什么导致的？谢谢

**Comment by panghaoyu** [comment]
感谢您的回复
